### ISSUE TITLE
r crashes when using getnext()

### ISSUE THREAD

**Issue by oldoldjiang** [randy3k/iterpc#2]
Hi, when I run the following code, my R crashes.
library(iterpc)
x = 'a'
tb = table(x)
iter = iterpc(tb, 1, ordered = TRUE, label = names(tb))
getall(iter) # only 1 element
getnext(iter) # get the element
getnext(iter) # hope to get NULL when iterator ends, but R crashes instead

However, when I reset x to have length == 2. Everything works well. 
x = c('a','b')
tb = table(x)
iter = iterpc(tb, 1, ordered = TRUE, label = names(tb))
getall(iter) # 2 element
getnext(iter) # get the first element
getnext(iter) # get the second element
getnext(iter) # Perfect

**Comment by randy3k** [comment]
Thanks for the report, will fix soon.

**Comment by randy3k** [comment]
It is now fixed at master. You could install the development version by
```r
devtools::install_github("randy3k/iterpc")
```
